source 'https://cdn.cocoapods.org'
source 'http://code.zaoing.com/meeting/freewindSpecs.git'
platform :ios, '9.0'

# 忽略引入库的所有警告
inhibit_all_warnings!
use_frameworks!

target 'VCSSDK_Example' do
  pod 'VCSSDK', :path => '../'

#  target 'VCSSDK_Tests' do
#    inherit! :search_paths
#
#    
#  end
end
